version: "3"
services:

  tensorflow-serving:
    image: serving_no_avx
    ports:
      - "8501:8501"
    command:
      - /usr/bin/tensorflow_model_server
      - --model_config_file=/models/models.config
      - --rest_api_port=8501
    volumes:
        - '/Users/kuba/serving/:/models'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.serving == true]